# Generated by Django 2.1.5 on 2020-06-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='locn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Location'),
        ),
    ]
