# Generated by Django 2.1.5 on 2020-06-18 15:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('work_type', models.CharField(choices=[('fulltime', 'Full-Time'), ('internship', 'Internship')], max_length=10, verbose_name='What opening suits you ?')),
                ('age', models.CharField(blank=True, choices=[('kiddo', 'Kiddo'), ('teen', 'Teenager'), ('legal', 'Legal'), ('mid-life crisis', 'Mid-Life Crisis'), ('boomer', 'Boomer')], max_length=20, null=True, verbose_name='What age you are bud ?')),
                ('pay', models.PositiveIntegerField(blank=True, null=True)),
                ('desc', ckeditor.fields.RichTextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Team')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_apld', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shorlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('resume', models.FileField(null=True, upload_to=jobs.models.res_store_dir_path)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Applicant')),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
    ]
