# Generated by Django 2.1.5 on 2020-06-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200618_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='age',
            field=models.CharField(blank=True, choices=[('kiddo', 'Kiddo'), ('Teen', 'Teenager'), ('Legal', 'Legal'), ('Mid-life crisis', 'Mid-Life Crisis'), ('Boomer', 'boomer')], max_length=20, null=True, verbose_name="Required candidate's age."),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('Full-Time', 'fulltime'), ('Internship', 'internship')], max_length=10, verbose_name='Opening Type.'),
        ),
    ]
