# Generated by Django 3.0.7 on 2020-06-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200619_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='age',
            field=models.CharField(blank=True, choices=[('kiddo', 'Kiddo'), ('teen', 'Teenager'), ('legal', 'Legal'), ('mid-life-crisis', 'Mid-Life Crisis'), ('boomer', 'Boomer')], max_length=20, null=True, verbose_name="Required candidate's age."),
        ),
    ]
