# Generated by Django 3.0.7 on 2020-06-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200621_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='age',
            field=models.CharField(blank=True, choices=[('kiddo', 'Kiddo'), ('teen', 'Teenager'), ('legal', 'Legal'), ('mid-life-crisis', 'Mid-Life Crisis'), ('boomer', 'Boomer')], max_length=20, null=True, verbose_name='Applicant Age'),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('fulltime', 'Full-Time'), ('internship', 'Internship')], max_length=10, verbose_name='Opening Type.'),
        ),
    ]
